# Use Rocky Linux 10 UBI Micro as the base image.
FROM rockylinux/rockylinux:10-ubi-micro

# Basic Image Info
LABEL author="Qian Qian <qubik65536@qubik65536.top>" \
      license="MIT" \
      name="benchy" \
      summary="The Docker image for Benchy, the submission timer & checker of the OJ System for CRC Robotics Programming Competition." \
      version="0.1.0" \

# Echo Hello World.
CMD echo "Hello World"
